# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0d721b8408f28a45b1abe95d2ca7ae5cbacaeb618cc77b3f5b37585028d12fe91c99d1ccfb700a9d44aff12ec29ff4106d48b9d7d8f1c32fa5cd96691aeb8f09

test:
  secret_key_base: 771044f83837f7dea50def2b1049f251360417b45c00bed06ddd4b087f74205b45c875e5d8bf30138eb622598cbde525d0e8a2e19e020e3d612c222bf90415cf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
